#!/bin/bash
# Script to extract tarball into src/ and write a commit message (with changelog).

scriptName=`basename "$0"`
tarballDirectory=~/Downloads/redobackup.snapshot.tarballs
tarballArray=( "snapshot-0.9.8.tar" "snapshot-0.9.9.tar" "snapshot-1.0.0.tar" "snapshot-1.0.1.tar" "snapshot-1.0.2.tar" "snapshot-1.0.3.tar" "snapshot-1.0.4.tar" )

for tarball in "${tarballArray[@]}"
do
  tarballSha256sum=$(sha256sum "$tarballDirectory/$tarball" | awk '{print $1}')


  echo "Extracting file $tarball"
  # Delete old src/ directory, as the latest snapshot is the complete 
  rm -rf src/ && mkdir src/
  tar -C src/ -xvf "$tarballDirectory/$tarball"
  git add src/

  changelog=$(<src/livecd/chroot/usr/share/redo/CHANGELOG)
  # Extract version string from changelog
  releaseDate=$(echo "$changelog" | head -n 2 | tail -n 1 | sed s_.*\(__g | sed s_\).*__g)

  # Extract top changelog entry (ie, most recent)
  lineNumberOfFirstBlankLine=$(echo "$changelog" | grep -E --line-number '^$' | head -n 1 | sed s_:*__g)
  mostRecentChangelogEntry=$(echo "$changelog" | head -n $lineNumberOfFirstBlankLine)

  git commit -F- <<EOF

Import Redo Backup and Recovery $tarball (released on $releaseDate)

Extracts Redo Backup and Recovery source code $tarball [1] [2] using
$scriptName, into the src/ directory.  Given the tarball
contains the complete source code for this release, to maintain correctness, 
the existing src/ directory was first deleted.

The CHANGELOG entry for this release [3] is attached below.  Please note, The
release tarball does not contain any kind of build automation which would
capture changes such as adding a new package with 'apt-get install'. An attempt
has been made to reconstruct this information by examining the CHANGELOG, and
the packages installed on the official ISO image uploaded to Sourceforge in
2011.

The ISO image produced by building this commit successfully boots, reaches the
desktop and launches the Redo Backup and Recovery frontend application.
However, limited testing has been conducted to confirm all functionality works
exactly the same as the official ISO image releases.

$mostRecentChangelogEntry

This commit was (initially) generated by $scriptName.

[1] sha256sum of $tarball: $tarballSha256sum
[2] https://sourceforge.net/projects/redobackup/files/src/
    https://web.archive.org/web/20190921123610/https://sourceforge.net/projects/redobackup/files/src/
[3] Extracted from $tarball's file livecd/chroot/usr/share/redo/CHANGELOG
EOF

done
